### ISSUE TITLE
Support wrap for attributes

### ISSUE THREAD

**Issue by Shinigami92** [Shinigami92/prettier-plugin-pug#2]
Currently all attributes of a tag are written in the same line.
We should wrap the attributes at a certain point. This can be the maximum line length (prettier's [`printWidth`](https://prettier.io/docs/en/options.html#print-width)) and / or a configurable number of attributes.
So if we configure `"maxAttributesBeforeWrap": 4`, attributes should be wrapped if there are more than 4.
The name of the option should be improved 😄, please suggest another one.

**Comment by Shinigami92** [comment]
@rdhar: What's your opinion about how I could implement wrapping?

I have some options:
- Wrap only attributes if there are more then 2 attributes
  - Should be configurable
  - The option `printWidth` is ignored completely
- Wrap with the `printWidth` option and consider the hole line
  - Could be hard to implement
  - Need to consider `printWidth` also for everything else

My last thoughts were to create a function that counts all attributes and if there are more than X, then wrap. But this would mean that I cant implement `printWidth` anymore (I think that `printWidth` is in generally not a good thing for pug 🤔 )

**Comment by rdhar** [comment]
Thanks for your patience, @Shinigami92.

If I go off a tangential example for a bit, here's an extract of TypeScript.

<details><summary>View TypeScript code extract...</summary>
<pre>class Student {
    fullName: string;

    constructor(
        public firstName: string,
        public middleInitial: string,
        public lastName: string,
        ) {
            this.fullName = firstName + ' ' + middleInitial + ' ' + lastName;
        }
    }
</pre></details>

Where the lines of interest are in the comma-separated list of `public ...`. Notice, in this form, Prettier formats them to be on 3 separated lines. Now rename/refactor `[F2]` them to have tiny names, e.g., `fN`, `mI` and `lN`. Notice that, this time, Prettier formats them to be all on one line.

From my experience, Prettier tries its best to squeeze everything together on one line, unless it exceeds 81 characters (at least in TypeScript's case), at which point everything gets their own line to respect `printWidth`.

Bringing it closer to home, let's a take a look at some HTML.
<details><summary>View HTML code extract...</summary>
<pre>&lt;img src="sample-image-of-an-uneventful-event-12.jpg" width="500" height="600" /&gt;
</pre></details>

Notice how Prettier gives each of the attributes their own line. Now, replace '12' with just '1' to observe the lines combine together into one since they're less than or equal to 81 characters in total.

I guess you can see where I'm getting at by now 😅. For maximum Prettier compatibility and consistency with other languages, `printWidth` should be respected when wrapping attributes exceeding a certain character limit, rather than the number of attributes themselves. Once again, personally, I'd be happy to happy to wrap anything more than 2 attributes into new lines automatically, but I don't think that's the preferred approach in general.

Fortunately, Pug makes it easy to have neat, multiline attributes separated by nothing more than spaces, as [laid out in their docs](https://pugjs.org/language/attributes.html#multiline-attributes). As for any one attribute that exceeds 81 characters by itself (e.g., a really, _really_ long image name), Prettier seems happy to leave it on one line for HTML, so there's at least no worry about force-wrapping these kind of longer lines into new lines.

_Only the faintest of silver lining to the cloud(!)_

**Comment by Shinigami92** [comment]
Oh my f*** god
That took only ~ 3 hours .-.
I'm so finished right now

Will release an alpha.7 for testing
If it's is stabel, I think I can release an RC.1 ^^

**Comment by rdhar** [comment]
So sorry for the hassle but, **really well done**! 👍 🎉

**Comment by Shinigami92** [comment]
[1.0.0-alpha.7](https://www.npmjs.com/package/prettier-plugin-pug) is now released
if you want you can test the **** out of it XD
I will go to bed 😴
